Added Project Documentation and EDA notebooks
aicoe-aiops/cloud-price-analysis-public pull request #2
Opened 2020-11-09 17:46 UTC by aakankshaduggal

## Related Issues and Dependencies

Related to issue #1, provides the documentation and initial analysis for the project - Cloud Price Analysis

## This introduces a breaking change

- [ ] Yes
- [x] No

## This Pull Request implements

Adds the Project Documentation for Project - Cloud Price Analysis and initial analysis notebooks for the same.

2020-11-09 17:50 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[3]:1:2: N816 variable 'unique_instanceType' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[5]:1:2: N816 variable 'unique_instanceType_frame' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[6]:1:2: N816 variable 'df_instanceType' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[7]:5:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[9]:1:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[10]:4:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[11]:2:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[12]:3:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[14]:18:9: F841 local variable 'locs' is assigned to but never used
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:1:1: F401 'json' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'ast' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'collections' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'pickle' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:11: E401 multiple imports on one line
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:6:1: F401 'numpy as np' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:10:1: F401 'statsmodels.graphics.mosaicplot.mosaic' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:11:1: F401 'matplotlib.colors.ListedColormap' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:12:1: F401 'seaborn as sns' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[2]:28:9: F841 local variable 'filepath' is assigned to but never used
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[2]:29:37: F821 undefined name 'json_data'
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[28]:2:5: F841 local variable 'numerical_features_list' is assigned to but never used
```
</details>

2020-11-09 18:45 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[3]:1:2: N816 variable 'unique_instanceType' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[5]:1:2: N816 variable 'unique_instanceType_frame' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[6]:1:2: N816 variable 'df_instanceType' in global scope should not be mixedCase
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[7]:5:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[9]:1:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[10]:4:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[11]:2:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[12]:3:5: F821 undefined name 'display'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[14]:18:9: F841 local variable 'locs' is assigned to but never used
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:1:1: F401 'json' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'ast' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'collections' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:1: F401 'pickle' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:4:11: E401 multiple imports on one line
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:6:1: F401 'numpy as np' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:10:1: F401 'statsmodels.graphics.mosaicplot.mosaic' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:11:1: F401 'matplotlib.colors.ListedColormap' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[1]:12:1: F401 'seaborn as sns' imported but unused
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[2]:28:9: F841 local variable 'filepath' is assigned to but never used
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[2]:29:37: F821 undefined name 'json_data'
notebooks/experimental/cloud-price-analysis-EDA.ipynb#In[28]:2:5: F841 local variable 'numerical_features_list' is assigned to but never used
```
</details>

2020-11-09 19:11 UTC, aakankshaduggal commented
/retest

2020-11-09 19:55 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[9]:1:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[14]:18:9: F841 local variable 'locs' is assigned to but never used
```
</details>

2020-11-09 19:56 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Failed
- hook id: flake8-nb
- exit code: 1

notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[9]:1:52: E712 comparison to True should be 'if cond is True:' or 'if cond:'
notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb#In[14]:18:9: F841 local variable 'locs' is assigned to but never used
```
</details>

2020-11-09 22:11 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Passed
```
</details>

2020-11-09 22:12 UTC, sesheta commented
<details>
<summary>Pre-Commit Test failed! Click here</summary>

```
[INFO] Initializing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Initializing environment for https://github.com/psf/black.
[INFO] Initializing environment for https://github.com/tomcatling/black-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Initializing environment for https://github.com/s-weigand/flake8-nb:pep8-naming.
[INFO] Installing environment for git://github.com/Lucas-C/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for git://github.com/pycqa/pydocstyle.git.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/pre-commit/mirrors-mypy.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/psf/black.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/tomcatling/black-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/s-weigand/flake8-nb.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
Tabs remover.............................................................Failed
- hook id: remove-tabs
- exit code: 1
- files were modified by this hook

Substituting tabs in: docs/Cloud-price-analysis.adoc by 4 whitespaces

Tabs have been successfully removed. Now aborting the commit.
You can check the changes made. Then simply "git add --update ." and re-commit

Trim Trailing Whitespace.................................................Failed
- hook id: trailing-whitespace
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc
Fixing docs/Forecasting.md

Check for merge conflicts................................................Passed
Fix End of Files.........................................................Failed
- hook id: end-of-file-fixer
- exit code: 1
- files were modified by this hook

Fixing docs/Cloud-price-analysis.adoc

Tests should end in _test.py.........................(no files to check)Skipped
Check for added large files..............................................Passed
check BOM - deprecated: use fix-byte-order-marker........................Passed
Check for case conflicts.................................................Passed
Check docstring is first.................................................Passed
Check JSON...............................................................Passed
Check for broken symlinks............................(no files to check)Skipped
Detect Private Key.......................................................Passed
Check python ast.........................................................Passed
Debug Statements (Python)................................................Passed
pydocstyle...............................................................Passed
Check Toml...............................................................Passed
Check Yaml...............................................................Passed
Fix End of Files.........................................................Passed
Trim Trailing Whitespace.................................................Passed
mypy.....................................................................Passed
black....................................................................Passed
black-nb.................................................................Failed
- hook id: black-nb
- files were modified by this hook

reformatted notebooks/experimental/cloud-price-analysis-EDA.ipynb
    32 cells reformatted, 12 cells left unchanged.
reformatted notebooks/experimental/cloud-price-analysis-indepth-EDA.ipynb
    11 cells reformatted, 5 cells left unchanged.
All done!
2 files reformatted.

flake8-nb................................................................Passed
```
</details>

2020-11-10 14:16 UTC, aakankshaduggal commented
/retest

2020-11-11 17:16 UTC, MichaelClifford requested changes

2020-11-11 17:16 UTC, MichaelClifford commented on docs/Forecasting.md
> +The aim of this project is to come up with a linear model that assumes a relationship between the input variable (month) and the predicted variable (Cost). Cost needs to be calculated from a linear c
Is developing a linear model the goal here? Or is it to generate an accurate forecast of costs based on current and previous cloud compute usage? Above you note that the initial approach will be a linear regression, but I'm not sure if you want to define that as the aim. You could updated it here to be a bit more specific, outlining the things you've already done in your forecasting notebook, like, "start by using a linear regression model on the existing timeseries data set that provides costs to project what those costs might be in the next 3 months" or something like that.

2020-11-11 17:16 UTC, MichaelClifford commented on docs/Forecasting.md
> +1. Linear Regression on Dummy Data
"Linear Regression on Sales Data" , or explain why Dummy data is needed here

2020-11-11 17:16 UTC, MichaelClifford commented on docs/Forecasting.md
> +[https://github.com/aicoe-aiops/cloud-price-analysis](https://github.com/aicoe-aiops/cloud-price-analysis)
Are these public?

2020-11-11 17:24 UTC, MichaelClifford commented
@aakankshaduggal were you able to get the Sesheta pre-commit test to pass locally?

2020-11-11 19:25 UTC, aakankshaduggal commented on docs/Cloud-price-analysis.adoc
> +. *Comparison through time:* AWS, Azure and other clouds change the price list every few days. Identifying new additions and changes to the price list (i.e drift analysis) would make it easier for a
This was specified by the Cost Management Team. I have removed "Drift Analysis" for now.

2020-11-11 19:29 UTC, aakankshaduggal commented on docs/Cloud-price-analysis.adoc
> +The completion of this project means AI CoE has a tool at the disposal of other Red Hat teams to use to predict the optimal way of managing cost.
This looks good :+1:

2020-11-11 19:29 UTC, aakankshaduggal commented on docs/Cloud-price-analysis.adoc
> +Given  a dataset that talks about the cloud needs of RedHat, build a Cost-Optimization model  that allows the user to make a wise decision on how cloud services should be managed with time. The model
Sure, on it

2020-11-11 21:14 UTC, aakankshaduggal commented on docs/Cloud-price-analysis.adoc
> +. https://docs.google.com/document/d/1hP3gMkQ6jSPNzDAoCC_QG6WNekJECXDZllxpko7Q924/edit?usp=sharing[Cost management forecasting and optimization with AI]  by Sergio Ocón-Cárdenas.
Nope, I'll remove this

2020-11-11 21:14 UTC, aakankshaduggal commented on docs/Cloud-price-analysis.adoc
> +. https://gitlab.cee.redhat.com/aduggal/modeling/-/tree/master/use_cases/cloud-price-analysis[https://gitlab.cee.redhat.com/aduggal/modeling/-/tree/master/use_cases/cloud-price-analysis]
I'll remove this as well

2020-11-12 17:53 UTC, aakankshaduggal commented
> @aakankshaduggal were you able to get the Sesheta pre-commit test to pass locally?

Yes

2020-11-18 18:40 UTC, aakankshaduggal commented
@MichaelClifford I have implemented the suggested changes.

2020-11-24 11:41 UTC, tumido commented
/retest

2020-11-24 11:45 UTC, tumido approved these changes
:+1: I like it! @MichaelClifford any objections or pending change requests?

2020-11-24 14:07 UTC, MichaelClifford reviewed
:ship: 
/approve

2020-11-24 14:07 UTC, MichaelClifford approved these changes

2020-11-24 16:40 UTC, merged